describe("Account Test", () => {
  beforeEach(() => {
    cy.visit("https://automationteststore.com/");
  });

  it("Test GET request", () => {
    cy.request({
      method: "GET",
      url: "https://dummyjson.com/products",
    }).then(res => {
      expect(res.status).to.eq(200);
      cy.log(JSON.stringify(res));
      cy.writeFile("cypress/fixtures/autogenerated/products.json", res.body);
    });
  });
});
